# name: Playwright Tests

# on:
#   push:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt 

#       - name: Install Playwright and dependencies
#         run: |
#           python -m playwright install  

#       - name: Run Playwright Tests
#         run: |
#           pytest 
      
#       - name: Upload HTML report
#         uses: actions/upload-artifact@v4
#         with:
#             name: playwright-html-report
#             path: reports/playwright-report.html

#       - name: Upload Playwright traces
#         uses: actions/upload-artifact@v4
#         with:
#               name: playwright-traces
#               path: traces/