name: Playwright Tests

on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt includes 'pytest' and 'playwright'

      - name: Install Playwright and dependencies
        run: |
          python -m playwright install  # This installs the necessary browsers

      - name: Run Playwright Tests
        run: |
          pytest  # This will automatically use pytest.ini
      
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
            name: playwright-html-report
            path: reports/playwright-report.html
            
      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        with:
              name: playwright-traces
              path: traces/